server.port: 6788
# hosts for external data
host: 
  price: https://min-api.cryptocompare.com
  monero: http://localhost:38082
  lightning: https://localhost:8080
# reserve proof address
rp-address: 5BG7NvDurzu1Mnrb5akNfdZwrQK95m9g8JW61mnxbeFTDHHCoRmt8fQPuHjENNBSRKGtssLyH4xkrhbHKoSzquKpUFcgA3C
send-address: 5BG7NvDurzu1Mnrb5akNfdZwrQK95m9g8JW61mnxbeFTDHHCoRmt8fQPuHjENNBSRKGtssLyH4xkrhbHKoSzquKpUFcgA3C
mass-wallet-filename: mass-alice
# macaroon path
macaroon-path: /root/.lnd-regtest-1/data/chain/bitcoin/regtest/admin.macaroon
# Rate lock mode will lock rate for xmr -> btc swaps.
# Price confidence will allow greater freedom for flucuations.
# When not in rate lock mode it is possible for swaps to get rejected if it the server would take a
# loss beyond the threshold. While locked rates will never be rejected.
mode:
  rate-lock: false
  price-confidence: 0.95
# markup so we can pay the bills
# needs to be > 0.05 when not in rate lock mode to maintain profitablility
markup: 0.06
# payment thresholds in satoshis
min-pay: 10000
max-pay: 10000000
# set the log level
logging:
  level:
    web: DEBUG
    org:
      springframework: INFO
# remove stack trace from error response
server.error.include-stacktrace: never
# not a big fan of h2
# TODO: database upgrade
spring.datasource:
  url: jdbc:h2:file:./data
  driverClassName: org.h2.Driver
  username: sa  
  password: pass
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: update
# temp fix for mulitsig time outs
spring.mvc.async.request-timeout: -1
