### use with vscode plugin humao.rest client

### health check
GET http://localhost:6789/health

### monero quote
GET http://localhost:6789/quote/xmr
Content-Type: application/json

{
    "address": "54gqcJZAtgzBFnQWEQHec3RoWfmoHqL4H8sASqdQMGshfqdpG1fzT5ddCpz9y4C2MwQkB5GE2o6vUVCGKbokJJa6S6NSatn",
    "amount": 0.123,
    "multisigInfo": "MultisigV1bwAY2rp3BoFg91Y1LakiPnJHeBAw4gUW982iKbQAXxExGHRHKyx1vFQ5A9TtZ3LVmZ3aktcevNGUfWGZh4DNNePcFiG9qL3qFHAQjGVoambGKSNZGNCkog1Ky7nLENWmYoccezEnwQvF6sZ287ZFXHPkZ4S2RunnjSyKc6BnABzTcMVa",
    "preimageHash": [108,241,180,200,248,28,5,60,119,54,118,200,105,136,176,227,143,213,216,134,96,199,224,48,141,103,134,64,70,38,94,245]
}

### Validate Monero address
POST http://localhost:18082/json_rpc 
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "id":"0",
    "method":"validate_address", 
    "params": {
        "address":"42go2d3XqA9Mx4HjZoqr93BHspcMxwAUBivs3yJKV1FyTycEcbgjNyEaGNEcgnUE9DDDAXNanzB16YgMt88Sa8cFSm2QcHK",
        "any_net_type": true,
        "allow_openalias": true
        }
}

### Add hold invoice
POST https://localhost:8180/v2/invoices/hodl
Grpc-Metadata-macaroon: 

{
    "hash": [224, 199, 253,  44, 149, 34, 254, 240, 249, 243, 120, 108, 140, 190, 74,  38, 149, 157,  65,141, 117, 176,  47, 166, 199,  59, 185,  30, 217, 113, 161, 236],
    "value": "10000",
    "expiry": "600"
}

### Settle hold invoice
POST https://localhost:8180/v2/invoices/settle
Grpc-Metadata-macaroon: 

{
    "preimage": [0,   7, 139,  10,  57, 237, 235, 242,
  118, 158,  49,  50, 190, 190,  47, 105,
  129, 221,  23, 245,  73, 164, 155, 247,
  156, 161, 114, 203, 240,  65,  20,  53]
}

### perform xmr swap
POST http://localhost:6789/swap/xmr
Content-Type: application/json

{
    "hash": "2161997ea4adcaa2806c0a0e66f30b3ac48ed9f969108742a6b163148f5c7b6c"
}

### get balances of xmr wallet
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"get_balance","params":{"account_index":0,"address_indices":[0,0]}}

### is_multisig check for xmr wallet

POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"is_multisig"}

### xmr get_tx_proof

POST http://127.0.0.1:18082/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"get_tx_proof","params":{"txid":"03c12740cea72d8bfd94be86c083ba962470e06b6d32236589763b15c11f6487",
"address": "54gqcJZAtgzBFnQWEQHec3RoWfmoHqL4H8sASqdQMGshfqdpG1fzT5ddCpz9y4C2MwQkB5GE2o6vUVCGKbokJJa6S6NSatn"}}

### xmr get_transfers
POST http://127.0.0.1:18082/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"get_transfers","params":{"out":true,"account_index":0}}

### bitcoin quote
GET http://localhost:6789/quote/btc
Content-Type: application/json

{
    "paymentRequest": "",
    "refundAddress": ""
}


### create wallet
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"create_wallet","params":{"filename":"mass","language":"English"}}

### open wallet
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"open_wallet","params":{"filename":"d3e7e6cf4f67d131c692b6a58409590e51272de126c32e70c1c7be76bb9372e31629477168"}}


### close wallet
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"close_wallet","params":{"filename":"d3e7e6cf4f67d131c692b6a58409590e51272de126c32e70c1c7be76bb9372e31629477168"}}

### export multisig info
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"export_multisig_info"}

### sign multisig
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{
"jsonrpc":"2.0","id":"0","method":"sign_multisig",
    "params": {
        "tx_data_hex": ""
    }
}

### submit multisig
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{
"jsonrpc":"2.0","id":"0","method":"submit_multisig",
    "params": {
        "tx_data_hex": ""
    }
}

### transfer
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"transfer","params":{"destinations":[{"amount":122000000000,"address":"54gqcJZAtgzBFnQWEQHec3RoWfmoHqL4H8sASqdQMGshfqdpG1fzT5ddCpz9y4C2MwQkB5GE2o6vUVCGKbokJJa6S6NSatn"}],"account_index":0,"subaddr_indices":[0],"priority":0,"ring_size":11}}

### sweep all
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{
"jsonrpc":"2.0","id":"0","method":"sweep_all",
    "params":{      
        "address":"5BG7NvDurzu1Mnrb5akNfdZwrQK95m9g8JW61mnxbeFTDHHCoRmt8fQPuHjENNBSRKGtssLyH4xkrhbHKoSzquKpUFcgA3C","account_index":0,"priority":0,"ring_size":11
    }
}

### import multisig info
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"import_multisig_info", 
    "params": {
        "info": [""]
    }
}


### /swap/initialize

POST http://localhost:6789/swap/initialize/xmr
Content-Type: application/json

{
    "hash": "6cf1b4c8f81c053c773676c86988b0e38fd5d88660c7e0308d67864046265ef5",
    "makeMultisigInfo": "MultisigxV1Ym9MSP2PYiCLjoPjCaDdBL7zLKq3DfYkKEqubBeJTkVmAAUsZykie7xEL7rS6AE8A5Aua8Tmc9sVoVgkFEMwnqNYE49L2ewApb7YfAn3ffD7vxYiJRC9M9DKvDqYL98kgX7YXUHBweVEMfvEDgZnzKR5XeRDmPVUunPHpNUFgr3boh1U3cDtx9W2ocVGHzDxQKzTqW1UW2X8zTtttJWaygMBcEJ9"
}