### use with vscode plugin humao.rest client

### health check
GET http://localhost:6789/health

### monero quote
GET http://localhost:6789/quote/xmr
Content-Type: application/json

{
    "address": "56fK1PpmCjz5CEiAb8dbpyQZtpJ8s4B2WaXPqyFD2FU9DUobuSDJZztEPeppvAqT2DPWcdp7qtW6KasCbYoWJC7qBcwWrSH",
    "amount": 0.123,
    "multisigInfo": "MultisigV1QUMnWLpohJt1va3RiRZJ5sMGzRuMCRxLu2L2oLdXEU5jSudoWf2L1UTJ89NUTqFqiRLriB2toCzquARxagDXaBZsKEGVSu9suSobN2jR68fgp4c5doHbKsWExZHQ4UkqcBJhd24VxTA4mR2Yw2eDGpeQ1kR8EW6aMdtozYeNkhKmBt94",
    "preimageHash": [9,89,171,169,187,120,6,135,239,136,79,42,77,80,218,62,155,44,141,244,220,100,203,213,201,181,85,16,29,242,129,80]
}

### Validate Monero address
POST http://localhost:18082/json_rpc 
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "id":"0",
    "method":"validate_address", 
    "params": {
        "address":"42go2d3XqA9Mx4HjZoqr93BHspcMxwAUBivs3yJKV1FyTycEcbgjNyEaGNEcgnUE9DDDAXNanzB16YgMt88Sa8cFSm2QcHK",
        "any_net_type": true,
        "allow_openalias": true
        }
}

### Add hold invoice
POST https://localhost:8180/v2/invoices/hodl
Grpc-Metadata-macaroon: 

{
    "hash": [224, 199, 253,  44, 149, 34, 254, 240, 249, 243, 120, 108, 140, 190, 74,  38, 149, 157,  65,141, 117, 176,  47, 166, 199,  59, 185,  30, 217, 113, 161, 236],
    "value": "10000",
    "expiry": "600"
}

### Settle hold invoice
POST https://localhost:8180/v2/invoices/settle
Grpc-Metadata-macaroon: 

{
    "preimage": [0,   7, 139,  10,  57, 237, 235, 242,
  118, 158,  49,  50, 190, 190,  47, 105,
  129, 221,  23, 245,  73, 164, 155, 247,
  156, 161, 114, 203, 240,  65,  20,  53]
}

### perform xmr swap
POST http://localhost:6789/swap/xmr
Content-Type: application/json

{
    "hash": "2161997ea4adcaa2806c0a0e66f30b3ac48ed9f969108742a6b163148f5c7b6c"
}

### get balances of xmr wallet
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"get_balance","params":{"account_index":0,"address_indices":[0,0]}}

### xmr get_tx_proof

POST http://127.0.0.1:18082/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"get_tx_proof","params":{"txid":"03c12740cea72d8bfd94be86c083ba962470e06b6d32236589763b15c11f6487",
"address": "54gqcJZAtgzBFnQWEQHec3RoWfmoHqL4H8sASqdQMGshfqdpG1fzT5ddCpz9y4C2MwQkB5GE2o6vUVCGKbokJJa6S6NSatn"}}

### xmr get_transfers
POST http://127.0.0.1:18082/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"get_transfers","params":{"out":true,"account_index":0}}

### bitcoin quote
GET http://localhost:6789/quote/btc
Content-Type: application/json

{
    "paymentRequest": "lnbcrt1m1ps030ffpp5r877hx0zrezwsn3u35c0x3u9aytgsazs5068ddxj35u2r0rtdhmsdqqcqzpgxqzjcsp5a6dve7yvsvcg2ecfewecea8x8cztyx2m07xzvjgnr9pa06r28q0q9qyyssqc0xc82rtdt0m6n3xv3uvft65dvgh9kugz7d4089kryn28ty039y90pufhuzhmxs0rjhwt7mghscsu8mr7gna7j8lkem262u9y5sazlcpf92z4k",
    "refundAddress": "54gqcJZAtgzBFnQWEQHec3RoWfmoHqL4H8sASqdQMGshfqdpG1fzT5ddCpz9y4C2MwQkB5GE2o6vUVCGKbokJJa6S6NSatn"
}


### create wallet
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"create_wallet","params":{"filename":"mass","language":"English"}}

### open wallet
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"open_wallet","params":{"filename":"mass"}}


### close wallet
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"close_wallet","params":{"filename":"mass"}}

### transfer
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"transfer","params":{"destinations":[{"amount":3000000000000,"address":"5BG7NvDurzu1Mnrb5akNfdZwrQK95m9g8JW61mnxbeFTDHHCoRmt8fQPuHjENNBSRKGtssLyH4xkrhbHKoSzquKpUFcgA3C"}],"account_index":0,"subaddr_indices":[0],"priority":0,"ring_size":11}}

### is multisig
POST http://localhost:18083/json_rpc 
Content-Type: application/json

{"jsonrpc":"2.0","id":"0","method":"get_address"}

### /swap/initialize

POST http://localhost:6789/swap/initialize/xmr
Content-Type: application/json

{
    "hash": "0959aba9bb780687ef884f2a4d50da3e9b2c8df4dc64cbd5c9b555101df28150",
    "makeMultisigInfo": "MultisigxV1FMswKZDfXtq3kTzGePZpmoGfQXAUiTC3RSU7NewQKrbYU92SauVA1CGGu3HS7FC57WSkCeZn3dxhyMPAgBdnGgLBb2BiV1AvQkB2dM4TidHE7xReY5JPjBt3sDFBLGNj86nMagmSFgx7A9BgtAFq1KLCKU3B3Z21TjkQUjXD1BKbQCzUWcAnybmyviMfD8VuTRUiuW1FCGy43wQER4uMHQXafwbv",
    "exportMultisigInfo": "4d6f6e65726f206d756c7469736967206578706f727401b70058439c272cf7fb041b1190ce7e2bb408605a535c5d0ca2891db421e9b3c2d67c29b72fece158776b889db4c0d6cb26300e4fa16f6125d71046c7d98422173454cc9f35b194e32f61b771da70399d5163f9da5d54b54579ec4f8f4f647dec6fc11958217d58242542c3f696a63839f357f76aadd6862ffef9858dfe9df916e07c92dcac735a5a00a5c701231733e522a83dd66b20c8ddc749ad2d3cd70e6626fc2c9d6455c07302",
    "swapAddress" : "58j2ZN3eWJii3eTREshibxYRRW6dfDhi58WUwDUMoWWb4qetaSxzkWD8CF24bdk77DMJ9sYJvxDb3WphMTtxLNDFUtqRF2t"
}