# why is six scared of seven?
server.port: 6789
# hosts for external data
host: 
  price: https://min-api.cryptocompare.com
  monero: http://localhost:18082
  lightning: https://localhost:8180
# macaroon path
macaroon-path: /home/nigellchristian/.lnd2/data/chain/bitcoin/regtest/admin.macaroon
# markup so we can pay the bills
markup: 0.01
# set the log level
logging:
  level:
    web: DEBUG
    org:
      springframework: INFO
# remove stack trace from error response
server.error.include-stacktrace: never
# not a big fan of h2
# TODO: database upgrade
spring.datasource:
  #persist the data  
  url: jdbc:h2:file:/data/ 
  driverClassName: org.h2.Driver  
  username: sa  
  password: pass  
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect  
