# why is six scared of seven?
server.port: 6789
# price data api
host: 
  price: https://min-api.cryptocompare.com
  monero: http://192.168.0.156:18082
  lighting: https://localhost:8080
# markup so we can pay the bills
markup: 0.01
# set the log level
logging:
  level:
    web: DEBUG
# remove stack trace from error response
server.error.include-stacktrace: never
# not a big fan of h2
# TODO: database upgrade
spring.datasource:
  #persist the data  
  url: jdbc:h2:file:/data/ 
  driverClassName: org.h2.Driver  
  username: sa  
  password: pass  
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect  
