# why is six scared of seven?
server.port: 6789
# hosts for external data
host: 
  price: https://min-api.cryptocompare.com
  monero: http://localhost:18083
  lightning: https://localhost:8180
# reserve proof address
rp-address: 54gqcJZAtgzBFnQWEQHec3RoWfmoHqL4H8sASqdQMGshfqdpG1fzT5ddCpz9y4C2MwQkB5GE2o6vUVCGKbokJJa6S6NSatn
send-address: 54gqcJZAtgzBFnQWEQHec3RoWfmoHqL4H8sASqdQMGshfqdpG1fzT5ddCpz9y4C2MwQkB5GE2o6vUVCGKbokJJa6S6NSatn
mass-wallet-filename: mass
# macaroon path
macaroon-path: /home/rimuru/.lnd-regtest-2/data/chain/bitcoin/regtest/admin.macaroon
# markup so we can pay the bills
markup: 0.01
# payment thresholds in satoshis
min-pay: 10000
max-pay: 10000000
# set the log level
logging:
  level:
    web: DEBUG
    org:
      springframework: INFO
# remove stack trace from error response
server.error.include-stacktrace: never
# not a big fan of h2
# TODO: database upgrade
spring.datasource:
  url: jdbc:h2:file:./data
  driverClassName: org.h2.Driver
  username: sa  
  password: pass
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: update
