DROP TABLE IF EXISTS MONERO_QUOTE;  
CREATE TABLE MONERO_QUOTE (  
quote_id INT AUTO_INCREMENT  PRIMARY KEY,  
amount FLOAT(100) NOT NULL,  
xmr_address VARCHAR(200) NOT NULL,
invoice VARCHAR(200) NOT NULL,
fulfilled BOOLEAN
);  